### PR TITLE
Html and Css Solo Project: Building with Backgrounds and Gradients.

### PR DESCRIPTION
**Pull request by Osong-Michael**
-This project was aimed at using gradients to create a contrast in colors on the navigation bar of the apple page.
-I used a linear gradient with 2 colors and making them 50% each to create the visuals you will see on the navigation bar.

### CODE REVIEW

**Comment by majovanilla** [comment]
# Code Review in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey @OA7 , 👋

## You did a *great* job on this project! 💜 

- Good Readme file
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...

- Your page is aligned to the left. It should be centered. The best way to align the elements inside the parent is to use `margin: auto`. This trick will be useful always! Please implement it in your `<body>`.

- Your `<main>` tag shouldn't enclose the nav. Check this [article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) to understand why (see usage section).

- The four images in the bottom should be links. 

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Use `<ul>` for navbars and footers. That way you create a list where every `<li>` element is the link. This is a very simple an common practice.

- Use `<span>` when you want to differentiate text elements in the same line. Check this [article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span). This could be useful for the left side of the footer.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by majovanilla** [comment]
Hello @OA7 

Nice work!! :muscle: 

You still need to center your page like the original one! That's the only thing missing before approving your project.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by uryelah** [comment]
Hello **Osong Agberndifor**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**You did a great job with the project and fixing the changes from the last CR! 🎇**
You are almost there, there are some issues you'll need to fix though.

---------    

**Great job at: 🥇** 
- using transition and pointer properties
- styling the text color, opacity and overall style
- being clever about matching the big text
- adding the icon and correct colors to the footer
- making a professional readme file

**You still need to fix the issues below before you can move to the next project**

---------

### Required changes 🛠 

- [ ] Make sure your HTML passes the validator before submitting a next code review request. There's a warning showing up at the moment [Test your mark up here](https://validator.w3.org/#validate_by_upload).

- [ ] The product display section should be aligned with the section above it. Compare your and the original version and fix the positioning.

Screenshot_2020-03-09 Apple Page clone
Screenshot_2020-03-09 Apple

- [ ] There's a small margin between the big image and the product one's bellow. Pay close attention to the screenshots above or check it in the [original site](https://validator.w3.org/nu/#textarea) and add it.

---------

### Optional enhancements

- [ ] [OPTIONAL] Make your transition more noticeable by changing it from 0.1s to a value between 0.15s and 0.3s. You can also add a time function. [Check this article for animation UX tips.](https://uxdesign.cc/the-ultimate-guide-to-proper-use-of-animation-in-ux-10bd98614fa9)

- [ ] [OPTIONAL] In a real site a user would expect to be able to click the whole nav area that looks like a button. Make it so the `<a>` tag takes 100% of the width and height of its parent `<div>`. 

- [ ] [OPTIONAL] Make the big text section and product section more semantic with a `<main>` and `<aside>` or `<section>` tags.

---------

**Please fix the required change 👷  before asking for a new code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by uryelah** [comment]
**Hey Osong, good job with most of the fixes. You are almost there.**
But the product margin issue still remains:

- [ ]  The product display section should be aligned with the section above it. Compare your and the original version and fix the positioning.
Screenshot_2020-03-09 Apple Page clone(1)

Try playing around a bit with the background-position and size and with the body margins.

---------

**Please fix the required change 👷  before asking for a new code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
